name: E2E

"on":
  workflow_dispatch:
    inputs:
      kne_ref:
        description: "openconfig/kne reference (tag, commit, branch)"
        type: string
        default: v0.1.9
        required: true
      kind_version:
        description: "KinD version"
        type: string
        required: true
        default: v0.17.0

env:
  GOVER: 1.20.2

jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          [
            "TestSrlinuxReconciler_BareSrlinuxCR",
            "TestSrlinuxReconciler_WithStartupConfig",
          ]

    steps:
      - name: Set env vars
        run: |
          echo "KNE_REF=${{ inputs.kne_ref }}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVER }}

      - name: Install kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          name: srl-test # cluster name
          version: ${{ inputs.kind_version }}
          skipClusterCreation: true

      - uses: actions/checkout@v3

      - name: Prepare e2e environment
        run: make prepare-e2e-env

      - name: Run e2e tests
        # this test ensures that srl-controller (built from referenced source) can be succesfully installed on a KNE cluster
        # for a using specified versions of KNE/KinD
        run: E2E_TEST_NAME=${{ matrix.test }} make test-e2e
